<?php
if (!$this->blogPosts == null) :
    /** @var app\code\models\BlogPosts $post */
    foreach ($this->blogPosts as $post) :
        ?>

        <div class="blog-post" role="group">
            <h2 class="blog-post-title"><?php echo $post->getPostTitle(); ?></h2>

            <p class="blog-post-meta"><?php echo $post->getPostDate(); ?> by <a
                    href="#">Mark</a></p>
            <?php echo $post->getPostText(); ?>
        </div>
        <hr/>
    <?php endforeach;
else : ?>
    Blog has no entries.
<?php endif; ?>
