<?php
use app\code\User;
if(User::isOnline()) :
?>
<form class="form-horizontal" action="<?php echo $this->getUrl('blog/admin/save'); ?>" method="post" role="form">
    <?php if($this->editable != null) : ?>
        <input type="hidden" name="id" id="blog_id" value="<?php echo $this->editable->getId();?>"/>
    <?php endif;?>
    <div class="form-group">
        <label for="blog_title" class="col-sm-4 control-label text-left">Blog Title</label>
        <div class="col-sm-8">
            <input type="text" class="form-control" name="BlogTitle" id="blog_title" placeholder="Title" value="<?php
            echo $this->editable ? $this->editable->getBlogTitle() : null; ?>">
        </div>
    </div>
    <div class="form-group">
        <label for="blog_post_limit" class="col-sm-4 control-label text-left">Blog Posts per page</label>
        <div class="col-sm-8">
            <input type="number" class="form-control" name="BlogPostLimit" id="blog_post_limit" placeholder="Posts per page" value="<?php
            echo $this->editable ? $this->editable->getBlogPostLimit() : null; ?>">
        </div>
    </div>
    <div class="form-group">
        <label for="blog_description" class="col-sm-4 control-label text-left">Blog Description</label>
        <div class="col-sm-8">
            <input type="text" class="form-control" name="BlogDescription" id="blog_description" placeholder="Description" value="<?php
            echo $this->editable ? $this->editable->getBlogDescription() : null; ?>">
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Save</button>
        </div>
    </div>
</form>
<?php endif; ?>