<?php
if ($this->post == null)
    return;
?>

    <div class="blog-post">
        <h2 class="blog-post-title"><?php echo $this->post->getPostTitle(); ?></h2>

        <p class="blog-post-meta"><?php echo $this->post->getPostDate(); ?> by
            <a href="#"><?php
                echo $this->post->getUser()->getUsername();?></a></p>
        <?php if ($this->post->getPostPicture() != null) : ?>
            <p class="img-thumbnail blog-post-meta">
                <img class="img-thumbnail"
                     src="<?php echo $this->getUpload($this->post->getPostPicture()); ?>" />
            </p>
        <?php endif; ?>
        <?php echo $this->post->getPostText(); ?>
    </div>
    <hr />
    <div class="panel panel-success">
        <div class="panel-heading">
            <h3 class="panel-title text-uppercase">Last comments</h3>
        </div>
        <div class="panel-body">
            <form class="form-horizontal" action="<?php
            echo $this->getUrl('blog/add/comment');?>" method="post" role="form">
                <input type="hidden" name="PostId" value="<?php echo $this->post->getId();?>"/>
                <div class="form-group">
                    <label for="name" class="col-sm-4 control-label text-left">Name</label>
                    <div class="col-sm-8">
                        <input type="text" class="form-control" name="Commentator" id="name" placeholder="Name" >
                    </div>
                </div>
                <div class="form-group">
                    <label for="comment" class="col-sm-4 control-label text-left">Comment</label>
                    <div class="col-sm-8">
                        <textarea class="form-control" name="Comment" id="comment" rows="3"></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-4 col-sm-8">
                        <button type="submit" class="btn btn-default">Add Comment</button>
                    </div>
                </div>
                </form>
            <?php
            $commentCollection = $this->post->getCommentCollection();
            if (!empty($commentCollection)) : ?>

                <hr/>
                <?php foreach ($commentCollection as $comment) : ?>
                    <div class="blog-post">
                        <h2 class="blog-post-title"><?php echo $comment->getCommentator(); ?></h2>

                        <p class="blog-post-meta"><?php echo $comment->getCommentDate(); ?></p>
                        <?php echo $comment->getComment(); ?>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>

    </div>
<hr/>
