<?php
use app\code\User;
if(User::isOnline()) :
?>
<form class="form-horizontal" action="<?php echo $this->getUrl('user/admin/save');?>" method="post" role="form">
    <input type="hidden" name="id" value="<?php echo $this->editable->getId();?>">
    <div class="form-group">
        <label for="username" class="col-sm-4 control-label text-left">Username</label>
        <div class="col-sm-8">
            <input type="text" class="form-control" name="username" id="username" placeholder="Username" value="<?php
            echo $this->editable ? $this->editable->getUsername() : null ;?>">
        </div>
    </div>
    <div class="form-group">
        <label for="email" class="col-sm-4 control-label text-left">Email</label>
        <div class="col-sm-8">
            <input type="email" class="form-control" name="email" id="email" placeholder="Email" value="<?php
            echo $this->editable ? $this->editable->getEmail() : null ;?>">
        </div>
    </div>
    <div class="form-group">
        <label for="password" class="col-sm-4 control-label text-left">New Password</label>
        <div class="col-sm-8">
            <input type="password" class="form-control" name="password" id="password" placeholder="New Password">
        </div>
    </div>
    <div class="form-group">
        <label for="firstname" class="col-sm-4 control-label text-left">Firstname</label>
        <div class="col-sm-8">
            <input type="text" class="form-control" name="firstname" id="firstname" placeholder="Firstname"  value="<?php
            echo $this->editable ? $this->editable->getFirstname() : null ;?>">
        </div>
    </div>
    <div class="form-group">
        <label for="lastname" class="col-sm-4 control-label text-left">Lastname</label>
        <div class="col-sm-8">
            <input type="text" class="form-control" name="lastname" id="lastname" placeholder="Lastname" value="<?php
            echo $this->editable ? $this->editable->getLastname() : null ;?>">
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Save</button>
        </div>
    </div>
</form>
<?php endif ;?>