<?php
use App\Code\User;

?>
<!DOCTYPE html>
<html>
<head lang="en">
    <title>Blog</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">

    <link rel="stylesheet" href="<?php echo $this::getCss('blog.css'); ?>">

    <!-- Latest compiled and minified JavaScript -->
    <script
        src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
</head>
<body>
<div class="blog-masthead">
    <div class="container">
        <nav class="blog-nav">
            <a class="blog-nav-item active" href="#">Aklesky's - Blog</a>
        </nav>
    </div>
</div>

<div class="container">

    <div class="blog-header">
        <h1 class="blog-title">Aklesky's Blog Service</h1>

        <p class="lead blog-description">The official example template of
            creating a blog with Bootstrap.</p>
    </div>

    <div class="row">

        <div class="col-sm-8 blog-main">

            <?php echo $this->content; ?>

        </div>
        <!-- /.blog-main -->

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
            <?php if (!User::isOnline()) : ?>
                <div class="sidebar-module sidebar-module-inset">
                    <form role="form" method="post"
                          action="<?php echo $this->getUrl('user/login'); ?>">
                        <h5>LOGIN</h5>

                        <div class="form-group">
                            <label for="login_email">Email address</label>
                            <input type="email" class="form-control"
                                   id="login_email" name="email"
                                   placeholder="Enter email">
                        </div>
                        <div class="form-group">
                            <label for="login_password">Password</label>
                            <input type="password" class="form-control"
                                   id="login_password" name="password"
                                   placeholder="Enter Password">
                        </div>
                        <button type="submit" class="btn btn-default">Submit
                        </button>
                    </form>
                </div>
            <?php else : ?>
            <div class="sidebar-module sidebar-module-inset">
                <div class="btn-group-vertical" role="group" aria-label="...">
                    <div class="dropdown" role="group">
                        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
                            Blog management
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="<?php echo $this->getUrl('blog/edit');?>">Blog settings</a></li>
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="<?php echo $this->getUrl('blog/new/post');?>">Add post</a></li>
                            <li role="presentation"><a role="menuitem" tabindex="-1" href="<?php echo $this->getUrl('blog/posts');?>">Posts</a></li>
                        </ul>
                    </div>
                    <p class="divider"></p>
                    <div class="btn-group" role="group">
                        <a href="<?php echo $this->getUrl('user/edit');?>" class="btn btn-block btn-default">My Account</a>
                    </div>
                </div>
                </div>
            <?php endif; ?>
        </div>
        <!-- /.blog-sidebar -->

    </div>
    <!-- /.row -->

</div>
<!-- /.container -->

<footer class="blog-footer">
    <p>Blog template built for <a href="http://getbootstrap.com">Bootstrap</a>
        by <a href="https://twitter.com/mdo">@mdo</a>.</p>

    <p>
        <a href="#">Back to top</a>
    </p>
</footer>

<script
    src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
<script src="<?php echo $this->getJs('form.js'); ?>"></script>
</body>
</html>