<?php
use App\Code\User;

?>
<!DOCTYPE html>
<html>
<head lang="en">
    <title><?php echo $this->settings->getBlogTitle();?></title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">

    <link rel="stylesheet" href="<?php echo $this::getCss('blog.css'); ?>">
    <link rel="stylesheet" href="<?php echo $this::getCss('fineuploader.css'); ?>">
    <link rel="stylesheet" href="<?php echo $this::getCss('preloader.css'); ?>">
    <!-- Latest compiled and minified JavaScript -->
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <?php if($this->getCanonicalUrl() != null) : ?>
    <link rel="canonical" href="<?php echo $this->getCanonicalUrl(); ?>" />
    <?php endif;?>
</head>
<body>
<div class="blog-masthead">
    <div class="container">
        <nav class="blog-nav">
            <a class="blog-nav-item active" href="<?php echo $this->getUrl('blog/index');?>">Aklesky's - Blog - Home</a>
            <?php if (!User::isOnline()) : ?>
                <div class="sidebar-module sidebar-module-inset">
                    <form role="form" method="post"
                          action="<?php echo $this->getUrl('user/login'); ?>">
                        <h5>LOGIN</h5>

                        <div class="form-group">
                            <label for="login_email">Email address</label>
                            <input type="email" class="form-control"
                                   id="login_email" name="email"
                                   placeholder="Enter email">
                        </div>
                        <div class="form-group">
                            <label for="login_password">Password</label>
                            <input type="password" class="form-control"
                                   id="login_password" name="password"
                                   placeholder="Enter Password">
                        </div>
                        <button type="submit" class="btn btn-default">Submit
                        </button>
                    </form>
                </div>
            <?php else : ?>
                <div class="sidebar-module sidebar-module-inset">
                    <div class="btn-group" role="group" aria-label="...">
                        <div class="dropdown" role="group">
                            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
                                Blog management
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                                <li role="presentation"><a role="menuitem" tabindex="-1" href="<?php echo $this->getUrl('blog/admin/settings');?>">Blog settings</a></li>
                                <li role="presentation"><a role="menuitem" tabindex="-1" href="<?php echo $this->getUrl('blog/admin/new/post');?>">Add post</a></li>
                                <li role="presentation"><a role="menuitem" tabindex="-1" href="<?php echo $this->getUrl('blog/admin/post/list');?>">Posts</a></li>
                            </ul>
                        </div>

                    </div>
                    <div class="btn-group" role="group" aria-label="...">
                        <div class="dropdown" role="group">
                            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
                                User management
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                                <li role="presentation"><a role="menuitem" tabindex="-1" href="<?php echo $this->getUrl('user/admin/list');?>">Users</a></li>
                                <li role="presentation"><a href="<?php echo $this->getUrl('user/admin/edit');?>" >My Account</a></li>
                            </ul>
                        </div>

                    </div>
                    <div class="btn-group" role="group">

                    </div>
                </div>
            <?php endif; ?>
        </nav>
    </div>
</div>

<div class="container">

    <div class="blog-header">
        <h1 class="blog-title"><?php echo $this->settings->getBlogTitle();?></h1>

        <p class="lead blog-description"><?php echo $this->settings->getBlogDescription();?></p>
    </div>

    <div class="row">

        <div class="col-sm-12 blog-main">

            <?php echo $this->content; ?>

        </div>

    </div>
    <!-- /.row -->

</div>
<!-- /.container -->

<footer class="blog-footer">
    <p>Blog template built for <a href="http://getbootstrap.com">Bootstrap</a>
        by <a href="https://twitter.com/mdo">@mdo</a>.</p>

    <p>
        <a href="#">Back to top</a>
    </p>
</footer>

<script
    src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
<script src="<?php echo $this->getJs("fileuploader/header.js");?>"></script>
<script src="<?php echo $this->getJs("fileuploader/util.js");?>"></script>
<script src="<?php echo $this->getJs("fileuploader/button.js");?>"></script>
<script src="<?php echo $this->getJs("fileuploader/handler.base.js");?>"></script>
<script src="<?php echo $this->getJs("fileuploader/handler.form.js");?>"></script>
<script src="<?php echo $this->getJs("fileuploader/handler.xhr.js");?>"></script>
<script src="<?php echo $this->getJs("fileuploader/uploader.basic.js");?>"></script>
<script src="<?php echo $this->getJs("fileuploader/dnd.js");?>"></script>
<script src="<?php echo $this->getJs("fileuploader/uploader.js");?>"></script>
<script src="<?php echo $this->getJs("fileuploader/jquery-plugin.js");?>"></script>

<script src="<?php echo $this->getJs('form.js'); ?>"></script>
</body>
</html>