<form class="form-horizontal" role="form">
    <div class="form-group">
        <label for="username" class="col-sm-2 control-label text-left">Username</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" name="username" id="username" placeholder="Username">
        </div>
    </div>
    <div class="form-group">
        <label for="email" class="col-sm-2 control-label text-left">Email</label>
        <div class="col-sm-10">
            <input type="email" class="form-control" name="email" id="email" placeholder="Email">
        </div>
    </div>
    <div class="form-group">
        <label for="password" class="col-sm-2 control-label text-left">Password</label>
        <div class="col-sm-10">
            <input type="password" class="form-control" name="password" id="password" placeholder="Firstname">
        </div>
    </div>
    <div class="form-group">
        <label for="firstname" class="col-sm-2 control-label text-left">Firstname</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" name="firstname" id="firstname" placeholder="Email">
        </div>
    </div>
    <div class="form-group">
        <label for="lastname" class="col-sm-2 control-label text-left">Lastname</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" name="lastname" id="lastname" placeholder="Lastname">
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Register</button>
        </div>
    </div>
</form>