<form class="form-horizontal" action="<?php echo $this->getUrl('blog/save'); ?>" method="post" role="form">
    <?php if($this->editable != null) : ?>
        <input type="hidden" name="id" id="blog_id" value="<?php echo $this->editable->getId();?>"/>
    <?php endif;?>
    <div class="form-group">
        <label for="blog_title" class="col-sm-4 control-label text-left">Blog Title</label>
        <div class="col-sm-8">
            <input type="text" class="form-control" name="BlogTitle" id="blog_title" placeholder="Title" value="<?php
            echo $this->editable ? $this->editable->getBlogTitle() : null; ?>">
        </div>
    </div>
    <div class="form-group">
        <label for="blog_description" class="col-sm-4 control-label text-left">Blog Description</label>
        <div class="col-sm-8">
            <input type="text" class="form-control" name="BlogDescription" id="blog_description" placeholder="Description" value="<?php
            echo $this->editable ? $this->editable->getBlogDescription() : null; ?>">
        </div>
    </div>
    <div class="form-group">
        <label for="blog_slug_tag" class="col-sm-4 control-label text-left">Slug Tag</label>
        <div class="col-sm-8">
            <input type="text" class="form-control" name="BlogSlugTag" id="blog_slug_tag" placeholder="Slug Tag" value="<?php
            echo $this->editable ? $this->editable->getBlogSlugTag() : null; ?>">
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Save</button>
        </div>
    </div>
</form>