<form class="form-horizontal" action="<?php echo $this->getUrl('blog/post/add');?>" method="post" role="form">
    <input type="hidden" name="BlogId" id="blog_id" value="1"/>
    <div class="form-group">
        <label for="post_title" class="col-sm-4 control-label text-left">Post Title</label>
        <div class="col-sm-8">
            <input type="text" class="form-control" name="PostTitle" id="post_title" placeholder="Post Title">
        </div>
    </div>
    <div class="form-group">
        <label for="post_url" class="col-sm-4 control-label text-left">Canonical Url</label>
        <div class="col-sm-8">
            <input type="url" class="form-control" name="PostUrl" id="post_url" placeholder="Post url">
        </div>
    </div>
    <div class="form-group">
        <label for="post_slug_tag" class="col-sm-4 control-label text-left">Slug Tag</label>
        <div class="col-sm-8">
            <input type="text" class="form-control" name="PostSlugTag" id="post_slug_tag" placeholder="Slug Tag">
        </div>
    </div>
    <div class="form-group">
        <label for="post_text" class="col-sm-2 control-label text-left">Post</label>
        <div class="col-sm-10">
            <textarea class="form-control" name="PostText" id="post_text" rows="3"></textarea>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Save</button>
        </div>
    </div>
</form>
<script type="text/javascript" src="<?php echo $this->getJs('tinymce/tinymce.min.js')?>"></script>
<script type="text/javascript">
    tinymce.init({
        selector: "textarea",
        plugins: [
            "advlist autolink lists link image charmap print preview anchor",
            "searchreplace visualblocks code",
            "media table contextmenu paste"
        ],
        toolbar: "styleselect | bold italic | alignleft aligncenter alignright | bullist numlist  link image"
    });
</script>