<form class="form-horizontal" action="<?php echo $this->getUrl('blog/edit');?>" method="post" role="form">
    <div class="form-group">
        <label for="blog_title" class="col-sm-2 control-label text-left">Blog Title</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" name="BlogTitle" id="blog_title" placeholder="Blog Title">
        </div>
    </div>
    <div class="form-group">
        <label for="blog_description" class="col-sm-2 control-label text-left">Blog Description</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" name="BlogDescription" id="blog_description" placeholder="Blog description">
        </div>
    </div>
    <div class="form-group">
        <label for="blog_slug_tag" class="col-sm-4 control-label text-left">Slug Tag</label>
        <div class="col-sm-8">
            <input type="text" class="form-control" name="BlogSlugTag" id="blog_slug_tag" placeholder="Blog Tag">
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Save</button>
        </div>
    </div>
</form>