<?php
use app\code\User;
if(User::isOnline()) :
?>
<form class="form-horizontal" action="<?php
echo $this->getUrl('blog/admin/save/post');?>" data-endpoint="<?php
echo $this->getUrl('blog/admin/upload');?>" method="post" role="form">
    <input type="hidden" name="BlogId" id="blog_id" value="<?php
    echo $this->editable ? $this->editable->getBlogId() : null;?>"/>
    <?php if($this->editable != null) : ?>
        <input type="hidden" name="id" id="post_id" value="<?php echo $this->editable->getId();?>"/>
    <?php endif;?>
    <div class="form-group">

        <label for="post_title" class="col-sm-4 control-label text-left">Post Title</label>
        <div class="col-sm-8">
            <div class="alert alert-danger hidden well-sm" role="alert">
                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                <span class="sr-only">Error:</span>
                <span class="alert-danger-msg"></span>
            </div>
            <input type="text" required="required" class="form-control" name="PostTitle" id="post_title" placeholder="Post Title" value="<?php
            echo $this->editable ? $this->editable->getPostTitle() : null; ?>">
        </div>
    </div>
    <div class="form-group">
        <label for="post_schedule" class="col-sm-4 control-label text-left">Post Schedule Date</label>
        <div class="col-sm-8">
            <input type="date" min="<?php echo date('Y-m-d');?>" class="form-control" name="PostSchedule" id="post_schedule" placeholder="Post Schedule date" value="<?php
            echo $this->editable ? $this->editable->getPostSchedule() : null; ?>">
        </div>
    </div>

    <div class="form-group">
        <label for="post_slug_tag" class="col-sm-4 control-label text-left">Slug Tag</label>
        <div class="col-sm-8">
            <div class="alert alert-danger hidden well-sm" role="alert">
                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                <span class="sr-only">Error:</span>
                <span class="alert-danger-msg"></span>
            </div>
            <input type="text" required="required" class="form-control" name="PostSlugTag" id="post_slug_tag" placeholder="Slug Tag" value="<?php
            echo $this->editable ? $this->editable->getPostSlugTag() : null; ?>">
        </div>
    </div>
    <div class="form-group">
        <label for="post_text" class="col-sm-2 control-label text-left">Post</label>
        <div class="col-sm-10">
            <textarea class="form-control" name="PostText" id="post_text" rows="3"><?php
                echo $this->editable ? $this->editable->getPostText() : null; ?></textarea>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-4 control-label text-left">Upload image</label>
        <div class="col-sm-6">
            <div id="manual-fine-uploader"></div>
        </div>
    </div>
    <?php if($this->editable) : ?>
        <div class="form-group">
            <div class="col-sm-offset-4 col-sm-8">
                <img class="img-thumbnail" src="<?php echo $this->getUpload($this->editable->getPostPicture());?>" />
            </div>
        </div>
<?php endif; ?>


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Save</button>
        </div>
    </div>
</form>
<?php endif;?>