<?php if ($this->collection !== null) : ?>
    <nav>
        <ul class="pagination">
            <?php for ($i = 1; $i <= $this->pages; ++$i) : ?>
                <li>
                    <a href="<?php echo $this->getUrl('blog/' . $i); ?>"><? echo $i; ?></a>
                </li>
            <?php endfor; ?>
        </ul>
    </nav>
    <?php
    /**
     * @var $post App\Code\Models\BlogPosts
     */
    ?>
    <?php foreach ($this->collection as $post) : ?>
        <div class="blog-post">
            <h2 class="blog-post-title"><a href="<?php
                echo $this->getUrl('blog/view/' . $post->getPostSlugTag());?>"><?php echo $post->getPostTitle(); ?></a>
            </h2>

            <p class="blog-post-meta"><?php echo $post->getPostDate(); ?> by <a
                    href="#"><?php
                    echo $post->getUser()->getUsername();?></a></p>
            <?php if ($post->getPostPicture() != null) : ?>
                <p class="img-thumbnail blog-post-meta">
                    <img class="img-thumbnail"
                         src="<?php echo $this->getUpload($post->getPostPicture()); ?>" />
                </p>
            <?php endif; ?>
            <?php echo $post->getPostText(); ?>
        </div>
        <hr />
    <?php endforeach; ?>
    <nav>
        <ul class="pagination">
            <?php for ($i = 1; $i <= $this->pages; ++$i) : ?>
                <li>
                    <a href="<?php echo $this->getUrl('blog/' . $i); ?>"><? echo $i; ?></a>
                </li>
            <?php endfor; ?>
        </ul>
    </nav>
<?php else : ?>
    Blog has no entries.
<?php endif; ?>