<?php echo '<?xml version="1.0" encoding="UTF-8"?>'; ?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:mobile="http://www.google.com/schemas/sitemap-mobile/1.0">
    <?php if($this->collection != null ) : ?>
        <?php foreach($this->collection  as $post) : ?>
    <url>
        <loc><?php echo $this->getUrl('blog/view/'. $post->getPostSlugTag());?></loc>
    </url>
        <?php endforeach;?>
    <?php endif;?>
</urlset>